const STRATEGY_CAS = 'cas';
const STRATEGY_FACEBOOK = 'facebook';
const STRATEGY_GOOGLE = 'google';
const STRATEGY_GOOGLE_APPS = 'googleApps';
const STRATEGY_LDAP = 'ldap';
const STRATEGY_LOCAL = 'local';
const STRATEGY_SHIBBOLETH = 'shibboleth';
const STRATEGY_TWITTER = 'twitter';

// Classify all known authentication strategies
const STRATEGIES_LOCAL = [STRATEGY_LOCAL, STRATEGY_LDAP];
const STRATEGIES_EXTERNAL = [STRATEGY_CAS, STRATEGY_FACEBOOK, STRATEGY_GOOGLE, STRATEGY_GOOGLE_APPS, STRATEGY_SHIBBOLETH, STRATEGY_TWITTER];
const STRATEGIES_INSTITUTIONAL = [STRATEGY_CAS, STRATEGY_GOOGLE_APPS, STRATEGY_SHIBBOLETH];

const authConstants = {
  STRATEGY_CAS,
  STRATEGY_FACEBOOK,
  STRATEGY_GOOGLE,
  STRATEGY_GOOGLE_APPS,
  STRATEGY_LDAP,
  STRATEGY_LOCAL,
  STRATEGY_SHIBBOLETH,
  STRATEGY_TWITTER,
  STRATEGIES_LOCAL,
  STRATEGIES_EXTERNAL,
  STRATEGIES_INSTITUTIONAL,
};

export { authConstants };
