/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface HomeNav {
        "image": string;
    }
    interface HomeSearch {
    }
    interface OaeDashboard {
    }
    interface OaeHomepage {
    }
    interface OaeNewsfeed {
    }
    interface OaeSidebar {
        "image": string;
    }
    interface OaeTag {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLHomeNavElement extends Components.HomeNav, HTMLStencilElement {
    }
    var HTMLHomeNavElement: {
        prototype: HTMLHomeNavElement;
        new (): HTMLHomeNavElement;
    };
    interface HTMLHomeSearchElement extends Components.HomeSearch, HTMLStencilElement {
    }
    var HTMLHomeSearchElement: {
        prototype: HTMLHomeSearchElement;
        new (): HTMLHomeSearchElement;
    };
    interface HTMLOaeDashboardElement extends Components.OaeDashboard, HTMLStencilElement {
    }
    var HTMLOaeDashboardElement: {
        prototype: HTMLOaeDashboardElement;
        new (): HTMLOaeDashboardElement;
    };
    interface HTMLOaeHomepageElement extends Components.OaeHomepage, HTMLStencilElement {
    }
    var HTMLOaeHomepageElement: {
        prototype: HTMLOaeHomepageElement;
        new (): HTMLOaeHomepageElement;
    };
    interface HTMLOaeNewsfeedElement extends Components.OaeNewsfeed, HTMLStencilElement {
    }
    var HTMLOaeNewsfeedElement: {
        prototype: HTMLOaeNewsfeedElement;
        new (): HTMLOaeNewsfeedElement;
    };
    interface HTMLOaeSidebarElement extends Components.OaeSidebar, HTMLStencilElement {
    }
    var HTMLOaeSidebarElement: {
        prototype: HTMLOaeSidebarElement;
        new (): HTMLOaeSidebarElement;
    };
    interface HTMLOaeTagElement extends Components.OaeTag, HTMLStencilElement {
    }
    var HTMLOaeTagElement: {
        prototype: HTMLOaeTagElement;
        new (): HTMLOaeTagElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "home-nav": HTMLHomeNavElement;
        "home-search": HTMLHomeSearchElement;
        "oae-dashboard": HTMLOaeDashboardElement;
        "oae-homepage": HTMLOaeHomepageElement;
        "oae-newsfeed": HTMLOaeNewsfeedElement;
        "oae-sidebar": HTMLOaeSidebarElement;
        "oae-tag": HTMLOaeTagElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface HomeNav {
        "image"?: string;
    }
    interface HomeSearch {
    }
    interface OaeDashboard {
    }
    interface OaeHomepage {
    }
    interface OaeNewsfeed {
    }
    interface OaeSidebar {
        "image"?: string;
    }
    interface OaeTag {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "home-nav": HomeNav;
        "home-search": HomeSearch;
        "oae-dashboard": OaeDashboard;
        "oae-homepage": OaeHomepage;
        "oae-newsfeed": OaeNewsfeed;
        "oae-sidebar": OaeSidebar;
        "oae-tag": OaeTag;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "home-nav": LocalJSX.HomeNav & JSXBase.HTMLAttributes<HTMLHomeNavElement>;
            "home-search": LocalJSX.HomeSearch & JSXBase.HTMLAttributes<HTMLHomeSearchElement>;
            "oae-dashboard": LocalJSX.OaeDashboard & JSXBase.HTMLAttributes<HTMLOaeDashboardElement>;
            "oae-homepage": LocalJSX.OaeHomepage & JSXBase.HTMLAttributes<HTMLOaeHomepageElement>;
            "oae-newsfeed": LocalJSX.OaeNewsfeed & JSXBase.HTMLAttributes<HTMLOaeNewsfeedElement>;
            "oae-sidebar": LocalJSX.OaeSidebar & JSXBase.HTMLAttributes<HTMLOaeSidebarElement>;
            "oae-tag": LocalJSX.OaeTag & JSXBase.HTMLAttributes<HTMLOaeTagElement>;
        }
    }
}
